### ISSUE TITLE
Serious bug: adding target domain annotation boxes into rpn proposals

### ISSUE THREAD

**Issue by Liyw979** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#10]
https://github.com/krumo/Domain-Adaptive-Faster-RCNN-PyTorch/blob/276fcf8ae41be483db94682722c8093703750fdd/maskrcnn_benchmark/engine/trainer.py#L137-L143

https://github.com/krumo/Domain-Adaptive-Faster-RCNN-PyTorch/blob/276fcf8ae41be483db94682722c8093703750fdd/maskrcnn_benchmark/modeling/rpn/inference.py#L147-L148

https://github.com/krumo/Domain-Adaptive-Faster-RCNN-PyTorch/blob/276fcf8ae41be483db94682722c8093703750fdd/maskrcnn_benchmark/modeling/rpn/inference.py#L51-L72

**Comment by krumo** [comment]
Hi @liyiwei979621500 Thanks for pointing it out. Actually during training you should generate target domain json with pseudo annotations like using [this script](https://github.com/krumo/Detectron-DA-Faster-RCNN/blob/master/tools/convert_cityscapes_to_unlabeled_caronly_coco.py). According to my experience, there is no difference on performance between using ground-truth annotations and pseudo annotations because of the random sampling strategy. But you are right, the gt_box should be filtered out if you plan to use the ground-truth annotations. This bug has been fixed in the recent commit.
